// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72oiTPicFze7Y0z10Gmt5FbFEzBmZyUY',
    appId: '1:255742010019:web:5f58e61e3dc1a31fad1516',
    messagingSenderId: '255742010019',
    projectId: 'bird-quizapp',
    authDomain: 'bird-quizapp.firebaseapp.com',
    storageBucket: 'bird-quizapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwMOAM4sfoxsNXFGzJdGQAAUIFC23QFI',
    appId: '1:255742010019:android:1cd9f8b5e1cf0134ad1516',
    messagingSenderId: '255742010019',
    projectId: 'bird-quizapp',
    storageBucket: 'bird-quizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5VWPzd5C1rlQ2GWxWKGI_huT1ZJb0cw',
    appId: '1:255742010019:ios:46c815445a535fffad1516',
    messagingSenderId: '255742010019',
    projectId: 'bird-quizapp',
    storageBucket: 'bird-quizapp.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5VWPzd5C1rlQ2GWxWKGI_huT1ZJb0cw',
    appId: '1:255742010019:ios:46c815445a535fffad1516',
    messagingSenderId: '255742010019',
    projectId: 'bird-quizapp',
    storageBucket: 'bird-quizapp.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );
}
